// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package health

import (
	"github.com/blackhorseya/user-app/internal/app/user/biz/health"
	"github.com/google/wire"
	"go.uber.org/zap"
)

import (
	_ "github.com/blackhorseya/gocommon/pkg/er"
)

// Injectors from wire.go:

func CreateIHandler(logger *zap.Logger, biz health.IBiz) (IHandler, error) {
	iHandler := NewImpl(logger, biz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
