// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRepo is an autogenerated mock type for the IRepo type
type IRepo struct {
	mock.Mock
}
