app:
  name: "user-app"
  env: "local"

http:
  port: 8080
  mode: debug

db:
  url: "mongodb://user-app:changeme@localhost:27017/user-db?connect=direct&authSource=admin"

log:
  encoding: console
  level: debug
